###############################################
############## MAGIC DOORS ####################
###############################################



############## DEBUG ##########################
debug: false
log.recipes.enable: true


############## MAGIC DOOR SETTINGS ############
magic.doors.recipe.name.root.door: root-door
magic.doors.recipe.name.door.copy: root-door-copy
magic.doors.recipe.name.door.key: door-key

  





############## RECIPES ############
recipes:
  - root-door
  - root-door-copy
  - door-key


###############################################
#################### ITEMS ####################
###############################################


################## BEGIN Root Door ############
recipe.root-door.name: √Root
recipe.root-door.rows: 
  - DDD
  - DID
  - DDD
recipe.root-door.mats: 
  - D=DIAMOND
  - I=IRON_DOOR
recipe.root-door.output: IRON_DOOR

recipe.root-door.listeners: 
  - com.blocktyper.magicdoors.RootDoorListener

################## BEGIN ROOT DOOR COPY #################
recipe.root-door-copy.name: ^RootDoorCopy
recipe.root-door-copy.rows: 
  - OEO
  - ODO
  - OWO
recipe.root-door-copy.mats: 
  - E=EMERALD
  - O=OBSIDIAN
  - W=WATER_BUCKET
  - D=IRON_DOOR
recipe.root-door-copy.output: IRON_DOOR
recipe.root-door-copy.item.starts.with: 
  - 4=√Root
recipe.root-door-copy.keep: 
  - NYN
  - NYN
  - NNN

################## END ROOT DOOR COPY #################




############ BEGIN Door Key ##########
recipe.door-key.name: ^DoorKey
recipe.door-key.rows: 
  - AYA
  - ADA
  - ALA
recipe.door-key.mats: 
  - Y=YELLOW_FLOWER
  - A=AIR
  - D=IRON_DOOR
  - L=LAVA_BUCKET
recipe.door-key.item.starts.with: 
  - 4=^RootDoorCopy
recipe.door-key.output: YELLOW_FLOWER
recipe.door-key.item.starts.with: []
recipe.door-key.keep: 
  - NNN
  - NYN
  - NNN
############ END Door Key ##########










magic.doors.door.name.prefixes: 
  - addicting
  - afraid
  - agreeable
  - amused
  - ancient
  - angry
  - annoyed
  - anxious
  - arrogant
  - ashamed
  - average
  - awful
  - bad
  - beautiful
  - better
  - big
  - bitter
  - black
  - blue
  - boiling
  - brave
  - breezy
  - brief
  - bright
  - broad
  - broken
  - bumpy
  - calm
  - careful
  - charming
  - cheerful
  - chilly
  - clumsy
  - cold
  - colossal
  - combative
  - comfortable
  - confused
  - cooing
  - cool
  - cooperative
  - courageous
  - crazy
  - creepy
  - cruel
  - cuddly
  - curly
  - curved
  - damp
  - dangerous
  - deafening
  - deep
  - delightful
  - depressed
  - determined
  - dirty
  - disgusted
  - disturbed
  - dizzy
  - dry
  - dull
  - dusty
  - eager
  - early
  - elated
  - embarrassed
  - empty
  - encouraging
  - energetic
  - enthusiastic
  - envious
  - evil
  - excited
  - exuberant
  - faint
  - fair
  - faithful
  - fantastic
  - fast
  - fat
  - few
  - fierce
  - filthy
  - fine
  - flaky
  - flat
  - fluffy
  - foolish
  - forlorn
  - frail
  - frantic
  - fresh
  - friendly
  - frightened
  - funny
  - fuzzy
  - gentle
  - giant
  - gigantic
  - good
  - gorgeous
  - greasy
  - great
  - green
  - grieving
  - grubby
  - grumpy
  - handsome
  - happy
  - hard
  - harsh
  - healthy
  - heavy
  - helpful
  - helpless
  - high
  - hilarious
  - hissing
  - hollow
  - homeless
  - horrible
  - hot
  - huge
  - hungry
  - hurt
  - hushed
  - husky
  - icy
  - ill
  - immense
  - itchy
  - jealous
  - jittery
  - jolly
  - juicy
  - kind
  - large
  - late
  - lazy
  - light
  - little
  - lively
  - lonely
  - long
  - loose
  - loud
  - lovely
  - low
  - lucky
  - magnificent
  - mammoth
  - many
  - massive
  - melodic
  - melted
  - mighty
  - miniature
  - moaning
  - modern
  - mute
  - mysterious
  - narrow
  - nasty
  - naughty
  - nervous
  - new
  - nice
  - nosy
  - numerous
  - nutty
  - obedient
  - obnoxious
  - odd
  - old
  - orange
  - ordinary
  - outrageous
  - panicky
  - perfect
  - petite
  - plastic
  - pleasant
  - precious
  - pretty
  - prickly
  - proud
  - puny
  - purple
  - purring
  - quaint
  - quick
  - quickest
  - quiet
  - rainy
  - rapid
  - rare
  - raspy
  - ratty
  - red
  - relieved
  - repulsive
  - resonant
  - ripe
  - roasted
  - robust
  - rotten
  - rough
  - round
  - sad
  - salty
  - scary
  - scattered
  - scrawny
  - screeching
  - selfish
  - shaggy
  - shaky
  - shallow
  - sharp
  - shivering
  - short
  - shrill
  - silent
  - silky
  - silly
  - skinny
  - slimy
  - slippery
  - slow
  - small
  - smart
  - smiling
  - smooth
  - soft
  - solid
  - sore
  - sour
  - spicy
  - splendid
  - spotty
  - square
  - squealing
  - stale
  - steady
  - steep
  - sticky
  - stingy
  - straight
  - strange
  - striped
  - strong
  - stupendous
  - successful
  - sweet
  - swift
  - tall
  - tame
  - tan
  - tart
  - tasteless
  - tasty
  - tender
  - tender
  - tense
  - terrible
  - testy
  - thirsty
  - thoughtful
  - thoughtless
  - thundering
  - tight
  - tiny
  - tired
  - tough
  - tricky
  - troubled
  - ugliest
  - ugly
  - uneven
  - upset
  - uptight
  - vast
  - victorious
  - vivacious
  - voiceless
  - wasteful
  - watery
  - weak
  - weary
  - wet
  - whispering
  - wicked
  - wide
  - wide-eyed
  - witty
  - wonderful
  - wooden
  - worried
  - x-ray
  - yellow
  - young
  - yummy
  - zany

magic.doors.door.name.suffixes: 
  - potter
  - snake
  - wizard
  - magi
  - noble
  - nightly
  - turing
  - asimov
  - heinlin
  - martin
  - rowling
  - tolkien
  - gaiman
  - piccard
  - riker
  - atwood
  - vonnegut
  - palinuk
  - sidharth
  - dragon
  - donkey
  - lannister
  - stark
  - steve
  - alex
















  
  
  
  
  
  