name: MagicDoors
version: 1.1.4
main:  com.blocktyper.magicdoors.MagicDoorsPlugin
author: spaarkimus
website: blocktyper.com
database: false
description: These doors are magic.
commands:
  md-equip:
    description: Gives OP stuff to test magic doors!